before:
  hooks:
    - go mod download
    - go generate ./...
archives:
  - id: tar
    builds:
    - darwin
    - linux
brews:
  - ids:
      - darwin
    tap:
      owner: attachmentgenie
      name: github-projects
builds:
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
