# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubProjects < Formula
  desc ""
  homepage ""
  version "0.8.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/attachmentgenie/github-projects/releases/download/v0.8.0/github-projects_0.8.0_darwin_amd64.tar.gz"
      sha256 "a1e096724eed731d53b1ee184d0f6dbb2a50ecfb34ef4767d8d4df313276f451"

      def install
        bin.install "github-projects"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/attachmentgenie/github-projects/releases/download/v0.8.0/github-projects_0.8.0_darwin_arm64.tar.gz"
      sha256 "f20fa6b4a4859d661d264ba35e92c6652f8f543765c430ba4b4602551c982dc2"

      def install
        bin.install "github-projects"
      end
    end
  end
end
